### ISSUE TITLE
Error on yo drupaltheme

### ISSUE THREAD

**Issue by rawzone** [pixelmord/generator-drupaltheme#2]
Im having a problem with running yo drupaltheme:

```
-> % yo drupaltheme

/usr/local/lib/node_modules/generator-drupaltheme/app/index.js:27
  '\n   `---------´  |    ' + 'Welcome to Yeoman,'.yellow.bold + '    |' +
                                                         ^
TypeError: Cannot read property 'bold' of undefined
    at DrupalthemeGenerator.askFor (/usr/local/lib/node_modules/generator-drupaltheme/app/index.js:27:58)
    at next (/usr/local/lib/node_modules/generator-drupaltheme/node_modules/yeoman-generator/lib/base.js:275:18)
    at DrupalthemeGenerator.run (/usr/local/lib/node_modules/generator-drupaltheme/node_modules/yeoman-generator/lib/base.js:289:4)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/env.js:433:20)
    at init (/usr/local/lib/node_modules/yo/bin/yo:98:7)
    at pre (/usr/local/lib/node_modules/yo/bin/yo:110:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/bin/yo:135:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Looks like other generators have had the same issues:
https://github.com/yeoman/generator-webapp/issues/137

Let me know if i can supply any more info.

**Comment by derSebastian** [comment]
Hi I have the same issue, but all my other generators run fine. I have updated the yeoman-generator, cleaned the npm cache, and reinstalled the drupaltheme generator; etc. Still no luck. Any suggestions?

**Comment by benmcginnis** [comment]
I'm having the same issue with a completely fresh install of node, npm, yeoman and drupal theme generator

**Comment by pixelmord** [comment]
Thanks for the infos, will attempt to implement a fix this week.
